[package]
name = "cubo"
version.workspace = true
edition.workspace = true

[lib]
name = "cubo_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-updater = "2"
tauri-plugin-process = "2"
serde_json = "1"
tracing = { workspace = true }
cubo-engine = { path = "../../../crates/cubo-engine" }
