[package]
name = "cubo-cli"
version.workspace = true
edition.workspace = true

[[bin]]
name = "cubo-cli"
path = "src/main.rs"

[dependencies]
cubo-engine = { path = "../cubo-engine" }
clap = { version = "4", features = ["derive"] }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
reqwest = { workspace = true }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt", "registry"] }
